
--- simple client-server model from the following paper:
--- José Meseguer, The Temporal Logic of Rewriting: A Gentle Introduction, LNCS 5065, 2008

mod CLIENT-SERVER is
    protecting NAT .
    sorts Oid Nat? Cnts Conf .
    subsort Nat < Nat? .
    subsort Cnts < Conf .

    op nil : -> Nat? [ctor] .
    ops a b c : -> Oid [ctor] .
    op f : Oid Oid Nat -> Nat [ctor] .
    op `{_`,_`} : Oid Nat -> Cnts [ctor] .

    op _<-_ : Oid Cnts -> Conf [ctor] .
    op `[_`] : Oid -> Conf [ctor] .
    op `[_`,_`,_`,_`] : Oid Oid Nat Nat? -> Conf [ctor] .

    op null : -> Conf [ctor] .
    op __ : Conf Conf -> Conf [ctor assoc comm id: null] .

    vars C S I : Oid .  vars N M : Nat .
    var W : Nat? .  var CNT : Cnts . 

    --- The followings are the rewriting rules to describe the behaviour
    --- of this system. The localized fairness for this model is specified
    --- in the metadata rule attributes.

    --- weak fairness localized to the variable C
    rl [req] : [C,S,N,nil] => [C,S,N,nil] (S <- {C,N}) 
         [metadata "just(C)"] .  

    --- strong fairness localized to the variables S and C
    rl [reply] : (S <- {C,N}) [S] => [S] (C <- {S,f(S,C,N)}) 
         [metadata "fair(S,C)"] .  

    --- strong fairness localized to the variable C. In addition,
    --- the item "rec" is specified to use the action of the form "rec".
    rl [rec] : (C <- {S,M}) [C,S,N,W] => [C,S,N,M] [metadata "rec; fair(C)"] .

    rl [dupl] : (I <- CNT) => (I <- CNT) (I <- CNT)  .
    rl [loss] : I <- CNT => null  .
endm

--- Full-Maude interface for LTLR model checknig under parameterized fairness
load ltlr-interface

(mod CLIENT-SERVER-CHECK is
  inc CLIENT-SERVER .
  pr SATISFACTION .

  subsort Conf < State .

  op init : -> State .
  eq init = [a] [b,a,1,nil] [c,a,0,nil] . 

  var CNT : Cnts .  vars C S I : Oid .  vars N : Nat . 

  *** abstraction
  eq (I <- CNT) (I <- CNT) = (I <- CNT) .
  *** extra rules below added by coherence completion
  rl [reply] : (S <-{C,N}) [S] => (S <-{C,N}) [S] (C <-{S,f(S,C,N)}) .
endm)

set verbose on .

--- false. Note that the action pattern "rec" is defined by the rule attribute.
(mc init |= <> rec .)

--- false. (only for ground weak fairness)
(mc init |= <> rec under
    (just : enabled(req(b)) => req(b)) ;
    (just : enabled(reply(a,b)) => reply(a,b)) ;
    (just : enabled(rec(b)) => rec(b))
.)

--- true. (ground weak and strong fairness)
(mc init |= <> rec under
    (just : enabled(req(b)) => req(b)) ;
    (fair : enabled(reply(a,b)) => reply(a,b)) ;
    (fair : enabled(rec(b)) => rec(b))
.)

--- true. (under strong/weak localized fairness)
(pfmc init |= <> rec .)

